plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: pconrad/ucsb-cs-jekyll-theme-try2

url: https://ucsb-cs56.github.io # the base hostname & protocol for your site
baseurl: /f18  # the subpath of your site, e.g. "/blog"


include:
  - _pages
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
  - .bundle

course: "CS56"
qtr: "F18"
qxx: "f18"
quarter: "Fall 2018"
piazza_url: https://piazza.com/class/jkq2p768nf6xb
gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=31412
github_org_name: ucsb-cs56-f18
github_org_url: https://github.com/ucsb-cs56-f18

ta_list: "Santha and Jinjin"
ta_list_full: "Santha Meena Ramamoorthy and Jinjin Shao"
mentors_list: "Daniel, Meredith, Rachel, Ryan, Sasha and Wei Tung"
discussion_section_times: "5pm,&nbsp;6pm,&nbsp;7pm"

github_url: https://github.com/ucsb-cs56/f18
mentor_url: https://ucsb-cs56-pconrad-mentors.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

legacy_wiki_url: https://foo.cs.ucsb.edu/56wiki
legacy_wiki_name: "56wiki"

submit_cs_course: TBD

start_week: 0
start_date: 2018-09-23 00:00:00.00-8:00
num_weeks: 11
extra_exam_week: true
sections: "5pm,&nbsp;6pm,&nbsp;7pm"

cal_dates: >
  [
    {"label":"F18 official start date", "date":"2018-09-23" },
    {"label":"F18 1st day of instruction", "date":"2018-09-27" },	
    {"label":"Univ Holiday", "date":"2018-11-12" },
    {"label":"Univ Holiday", "date":"2018-11-22" },
    {"label":"Univ Holiday", "date":"2018-11-23" },
    {"label":"F18 instruction ends", "date":"2018-12-07" },
    {"label":"F18 finals start", "date":"2018-12-08" },
    {"label":"F18 finals end", "date":"2018-12-14" },
    {"label":"F18 qtr ends", "date":"2018-12-14" }
  ]

hwk_drop_lowest: three

legacy_wiki_name: 56wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/56wiki" 


hfj_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfj/HFJ_Chapter_"
hfdp_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfdp/HFDP_Chapter_"

kramdown:
   parse_block_html: true


exclude:
   - vendor
   - _exam/e02/cs56_m16_e02/code
   - _exam/e01/cs56_f16_e01/code


timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
